server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: api-service

logging:
  level:
    org.exampledriven.eureka: DEBUG