server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: author-service

logging:
  level:
    org.exampledriven.eureka.customer.shared.CustomerServiceFeignClient: FULL
    org.exampledriven.eureka: DEBUG


    
