server:
  port: ${PORT:8761}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false

security:
  user:
    name: ${EUREKA_USER_NAME}
    password: ${EUREKA_PASSWORD}
